version: 2 
sources:
  - name: raw 
    database: BLAZING_MART
    schema: raw
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    tables:
      - name: orders
      - name: shipments
      - name: customers
      - name: hubs  
      - name: costs

models:
  - name: stg_shipments
    description: "Cleaned shipment data with standardized columns."
    columns:
      - name: shipment_id
        description: "Unique identifier for each shipment."
        tests:
          - unique
          - not_null

      - name: order_id
        description: "Identifier linking to the corresponding order."
        tests:
          - not_null

      - name: promised_days
        description: "Number of days promised for delivery."
        tests:
          - not_null

      - name: shipped_date
        description: "Date when the shipment was sent."
        tests:
          - not_null

      - name: delivered_date
        description: "Date when the shipment was delivered."

  - name: stg_customers
    description: "Cleaned customer data with standardized columns."
    columns:
      - name: customer_id
        description: "Unique identifier for each customer."
        tests:
          - unique
          - not_null

      - name: signup_date
        description: "Date when the customer signed up."
        tests:
          - not_null

      - name: customer_type
        description: "Type of customer (e.g., regular, premium)."
        tests:
          - not_null

      - name: loyalty_status
        description: "Loyalty status of the customer (e.g., gold, silver)."
        tests:
          - not_null
          - accepted_values:
              values: ['yes','no']


  - name: stg_hubs
    description: "Cleaned hub data with standardized columns."
    columns:
      - name: hub_id
        description: "Unique identifier for each hub."
        tests:
          - not_null

      - name: hub_city
        description: "City where the hub is located."
        tests:
          - not_null

      - name: daily_shipment_capacity
        description: "Daily shipment capacity of the hub."
        tests:
          - not_null