version: 2 
sources:
  - name: raw 
    database: BLAZING_MART
    schema: raw
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    tables:
      - name: orders
      - name: shipments
      - name: customers
      - name: hubs  
      - name: costs